services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    ports:
      - 9229:9229
